      SUBROUTINE RDHIST(IEVERY,TFIND)

c reads history tapes.  If every=0, read until time tfind;
c if every=1, read next record only.  tfind=time of record to be found

c if natm=0, read/write ocean dynamics only
c if natm=1, do ocean dynamics plus ssta
c if natm=2, do full coupled ocean/atmospere
 
      INTEGER OUTHST
      INCLUDE 'zeq.common'
 
      COMMON/ZDATA/WM(30,34,2,12),DIVM(30,34,12),Q0O(30,34),
     A SSTM(30,34,12),UO(30,34),VO(30,34),DO(30,34),HTAU(34,30,2),
     B WEM(30,34,12),TO(30,34),UV(30,34,2,12),US(30,34),VS(30,34),
     C WP(30,34),DT1(30,34,7),TT(30,34),UV1(30,34),UV2(30,34),
     D WM1(30,34),UAT(30,34),VAT(30,34),DIVT(30,34)

      COMMON/ZDAT2/H1(30,34),U1(30,34),V1(30,34)
      DATA  INHST/61/,OUTHST/62/
 
      IF(IEVERY .NE. 0) GO TO 10

      READ(INHST,ERR=99,END=100) TD,NT,NXP,NYP,NSEG,NX,NY,HEQUIV,TZERO,
     A TENDD,DTD,XWD,XED,YSD,YND,TDECAY,TPLMIN,TSTPRT,CHKSUM,
     A NPRINT,MASKW,MWNDGF,WMXW,WMXE,WMYS,WMYN,PERIOD,YNORTH,
     A YSOUTH,XWEST,NSEG,NTAPE,NREWND,NATM

      BACKSPACE INHST
      NSKIP = TFIND - TD + 0.5
      IF(NSKIP .LE. 0) GO TO 10
      DO 1 NNN=1,NSKIP
      READ(INHST,END=100)
      READ(INHST,END=100)
      READ(INHST,END=100)
1     CONTINUE
 
10    CONTINUE
      READ(INHST,ERR=99,END=100) TD,NT,NXP,NYP,NSEG,NX,NY,HEQUIV,TZERO,
     A TENDD,DTD,XWD,XED,YSD,YND,TDECAY,TPLMIN,TSTPRT,CHKSUM,
     A NPRINT,MASKW,MWNDGF,WMXW,WMXE,WMYS,WMYN,PERIOD,YNORTH,
     A YSOUTH,XWEST,NSEG,NTAPE,NREWND,NATM
      NS=NSEG+1
      READ(INHST,ERR=99,END=100) HEADER,(AKB(I),I=1,NXP),((UB(J,I),
     A J=1,NYP),I=1,NXP),((HB(J,I),J=1,NYP),I=1,NXP),(ABC(K),
     A ROSS(K),TR(K),K=1,NS),((V(J,I),J=1, NYP),I=1,NXP),((UBNDY(J,K),
     A J=1,NYP),K=1,NS),((HBNDY(J,K),J=1,NYP),K=1,NS)
      READ(INHST,ERR=99,END=100) Q0O,UO,VO,DO,TO,U1,V1,H1
      IF(IEVERY.NE.0) RETURN
      TTEST=0.5*DTD+TD
      IF(TTEST.LT.TFIND) GO TO 10
      GO TO 110
99    WRITE(6,98)
98    FORMAT(1X,'READ ERROR ON INPUT HISTORY FILE')
      GO TO 110
100   WRITE(6,101)
101   FORMAT(1X,'END-OF-FILE ON HISTORY INPUT')
110   WRITE(6,111) TFIND,TD,NT
111   FORMAT(1X,'RDHST SOUGHT TIME:',1X,F10.3,5X,'FOUND TIME:'1X,
     A F10.3,5X,'TIMESTEP:',1X,I6/)
      RETURN
 
      ENTRY WRHIST

c this is where the writing is done
 
      IF(MOD(NREWND,10).NE.0) REWIND OUTHST
      WRITE(OUTHST) TD,NT,NXP,NYP,NSEG,NX,NY,HEQUIV,
     A TZERO,TENDD,DTD,XWD,XED,YSD,YND,TDECAY,TPLMIN,TSTPRT,
     A CHKSUM,NPRINT,MASKW,MWNDGF,WMXW,WMXE,WMYS,WMYN,PERIOD,
     A YNORTH,YSOUTH,XWEST,NSEG,NTAPE,NREWND,NATM
      NS=NSEG+1
         WRITE(OUTHST)HEADER,(AKB(I),I=1,NXP),((UB(J,I),
     A J=1,NYP),I=1,NXP),((HB(J,I),J=1,NYP),I=1,NXP),(ABC(K),
     A ROSS(K),TR(K),K=1,NS),((V(J,I),J=1, NYP),I=1,NXP),((UBNDY(J,K),
     A J=1,NYP),K=1,NS),((HBNDY(J,K),J=1,NYP),K=1,NS)
      WRITE(OUTHST) Q0O,UO,VO,DO,TO,U1,V1,H1
205   WRITE(6,201) TD,NT
201   FORMAT(1X,' TIME ',F10.3, ' TIMESTEP ',I6, ' WRITTEN TO HISTORY
     A TAPE ')
      IF(MOD(NREWND,10).NE.0) REWIND OUTHST
      RETURN
      END
